// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHHrC6dV260TdJqH4xn5VeWWlbRWpcQEU',
    appId: '1:412044120587:web:8d2b79a0c9fd510eaf2d0e',
    messagingSenderId: '412044120587',
    projectId: 'kaamyaar-744f7',
    authDomain: 'kaamyaar-744f7.firebaseapp.com',
    storageBucket: 'kaamyaar-744f7.firebasestorage.app',
    measurementId: 'G-D9BJ6FM100',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvk7ZsI7eo__olUWyjap03z22TRfaRjG4',
    appId: '1:412044120587:android:8eb4737ba2c13a23af2d0e',
    messagingSenderId: '412044120587',
    projectId: 'kaamyaar-744f7',
    storageBucket: 'kaamyaar-744f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm8uBMtvvpJNfgKlJ4rdsfV5OyQShjz8s',
    appId: '1:412044120587:ios:559e824732077726af2d0e',
    messagingSenderId: '412044120587',
    projectId: 'kaamyaar-744f7',
    storageBucket: 'kaamyaar-744f7.firebasestorage.app',
    iosBundleId: 'com.example.kaamyaar',
  );
}
